/*
 * Copyright (c) 2022 Reva Technology Inc., all rights reserved.
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Licensed under the Elastic License 2.0; you may not use this file except
 * in compliance with the Elastic License 2.0.
 */

export const vacateReasonTranslationMapping = {
  AA: 'ANOTHER_APARTMENT_VACATE_REASON',
  BL: 'BROKEN_LEASE_VACATE_REASON',
  CA: 'CANCEL_VACATE_REASON',
  CC: 'COLLEGE_YEAR_VACATE_REASON',
  CO: 'CONDITION_APARTMENT_VACATE_REASON',
  DC: 'DEATH_CLAUSE_VACATE_REASON',
  EL: 'EXPIRED_LEASE_VACATE_REASON',
  ET: 'TRANSFER_VACATE_REASON',
  FI: 'FINANCIAL_ISSUES_VACATE_REASON',
  G1: 'HOUSEHOLD_CHANGE_VACATE_REASON',
  H1: 'NON_PAYMENT_VACATE_REASON',
  H2: 'ANOTHER_NON_PAYMENT_VACATE_REASON',
  H3: 'TENANT_INITIATED_VACATE_REASON',
  H4: 'FAMILY_DEATH_VACATE_REASON',
  H5: 'UNIT_CONTRACTS_TRANSFER_VACATE_REASON',
  MD: 'MANAGEMENT_DECISION_VACATE_REASON',
  PH: 'PURCHASED_HOUSE_VACATE_REASON',
  PP: 'PET_POLICY_VACATE_REASON',
  RE: 'RELOCATING_VACATE_REASON',
  RH: 'RENTED_HOUSE_VACATE_REASON',
  RI: 'RENTAL_INCREASE_VACATE_REASON',
  SK: 'SKIPPED_VACATE_REASON',
  TE: 'TENANT_EVICTED_VACATE_REASON',
  TR: 'UNIT_TRANSFER_VACATE_REASON',
  CV: 'COVID_LEASE_BREAK',
  '@@': 'UNKNOWN',
};
