/*
 * Copyright (c) 2022 Reva Technology Inc., all rights reserved.
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Licensed under the Elastic License 2.0; you may not use this file except
 * in compliance with the Elastic License 2.0.
 */

export const HIDDEN_FIELD_SUFFIX = 'HIDDEN';
export const ACTIVITY_LOG_SYMBOLS = {
  PARTY_SOURCE: 'Source',
  PARTY_SOURCE_TYPE: 'Source_Type',
  PARTY_PROGRAM: 'Program',
  PARTY_PROGRAM_PATH: 'Path',
  CAMPAIGN: 'Campaign',
  FIRST_CHANNEL: 'First_Channel',
  GUESTS: 'Guests',
  UNITS: 'Units',
  LEASING_AGENT: 'Leasing_Agent',
  DATE: 'Date',
  END_DATE: 'EndDate',
  STATUS: 'Status',
  NAME: 'Name',
  PREFERRED_NAME: 'Preferred Name',
  TYPE: 'Type',
  PHONES: 'Phones',
  EMAIL: 'Emails',
  EXISTING_QUOTE: 'Existing_Quote',
  QUOTE: `Quote_${HIDDEN_FIELD_SUFFIX}`,
  RENEWAL_LETTER_FOR_UNIT: 'Renewal_letter_for',
  MOVEOUT_NOTICE_SERVED_BY: 'Moveout notice served by',
  AT_DATE: 'At date',
  VACATE_DATE: 'Vacate date',
  ACTION: `Action_${HIDDEN_FIELD_SUFFIX}`,
  QUOTE_ID: 'Quote_ID',
  QUOTED_UNIT: 'Quoted_Unit',
  LEASE_ID: 'Contract',
  LEASED_UNIT: 'Leased_Unit',
  LEASE_START: 'Lease_Start',
  LEASE_TERMS: 'Lease_Terms',
  EXPIRATION_DATE: 'Expiration_Date',
  SELECTIONS: 'Selections',
  CONFIRMATION_NUMBER: 'Confirmation_Number',
  TO: 'To',
  FROM: 'From',
  PRIMARY_AGENT: 'Primary_Agent',
  PREVIOUS_PRIMARY_AGENT: 'Previous_Primary_Agent',
  STATE: 'State',
  CLOSE_REASON: 'Close_Reason',
  ARCHIVE_REASON: 'Archive_Reason',
  TASK_NAME: `Task_Name_${HIDDEN_FIELD_SUFFIX}`,
  ASSIGNEE: 'Assignee',
  CREATED_BY: 'Created_By',
  PARTY_OWNER: 'Owner',
  OWNER_TEAM: 'Team',
  COMPLETED_BY: 'Completed_By',
  REOPENED_BY: 'Reopened_By',
  DECLINED_BY: 'Declined_By',
  CONFIRMED_BY: 'Confirmed_By',
  APPROVER: 'Approver',
  UNIT: 'Unit',
  TIME: 'Time',
  LEASE_TERM: 'Lease_Term',
  DEPOSIT: 'Deposit',
  PAYMENT_METHOD: 'Payment_Method',
  NOTES: 'Notes',
  CONTACT_INFO: 'Contact_Info',
  RECURRING_AND_OR_ONE_TIME_CHARGES_EDITED: 'Recurring_and/or_One-time_charges_edited',
  CONTACT_EVENT: 'Contact_Event',
  PARTICIPANTS: 'Participants',
  ON_BEHALF_OF: 'On_behalf_of',
  SCORE: 'Score',
  APPOINTMENT_RESULT: 'APPOINTMENT_TOUR_RESULT',
  BY: 'By',
  FOR: 'For',
  BASE_RENT: 'Base_rent_change_to',
  LEASE_EDITS: 'Lease_changes',
  RECORDING_TYPE: `Recording_Type_${HIDDEN_FIELD_SUFFIX}`,
  HELD: 'On-Hold',
  MEMBER_NAME: 'memberName',
  PERSON_MERGE_TARGET: 'PersonMergeTarget',
  PERSON_MERGE_SOURCE: 'PersonMergeSource',
  PARTIES_MERGE_FIRST_PARTY_MEMBERS: 'PartiesMergeFirstPartyMembers',
  PARTIES_MERGE_SECOND_PARTY_MEMBERS: 'PartiesMergeSecondPartyMembers',
  PARTIES_MERGE_PARTY_OWNER: 'PartiesMergePartyOwner',
  PARTIES_MERGE_TARGET_MEMBERS: 'PartiesMergeTargetMembers',
  PARTIES_MERGE_SOURCE_MEMBERS: 'PartiesMergeSourceMembers',
  LENGTH: 'Length',
  INVENTORY_SHORTHAND: 'Inventory_Shorthand',
  CHANGED_BY: 'Changed_By',
  DAYS_RESERVED: 'Days_Reserved',
  AUTOMATICALLY: 'Automatically',
  APPLICATION_STATUS: 'Application_status',
  SCREENING_STATUS: 'Screening_status',
  PRIMARY_PROPERTY: 'Property',
  REASON: 'Reason',
  WAIVER_REASON: 'waiverReason',
  PREVIOUS_APP_STATUS: 'Previous_Application_Status',
  RESIDENTS: 'Residents',
  GUARANTORS: 'Guarantors',
  SSN_SET_FOR: 'SSN_set_for',
  SSN_ENABLED_FOR: 'SSN_enabled_for',
  PRIMARY_PROPERTY_UPDATED: 'Primary_Property_updated_to',
  CLOSING_NOTES: 'Closing_notes',
  INACTIVE_USER: 'Inactive_user',
  DEACTIVATED_IN_TEAM: 'Deactivated_in_team',
  COMM_DIRECTION: 'Communication_direction',
  DIRECTION: 'Direction',
  TO_NUMBER: 'To_Number',
  FROM_NUMBER: 'From_number',
  DURATION: 'Call_duration',
  RING_DURATION: 'Ring_duration',
  WORKFLOW_NAME: 'Name',
  SYNC_EVENT_TYPE: 'syncEventType',
  RENEWAL_STATUS: 'renewalStatus',
  SYNC_SUCCESSFUL: 'syncSuccessful',
  SUBJECT: 'Subject',
  LEASE_STATUS: 'Lease',
  DOWNLOAD_STATUS: 'Download_lease',
  NEW_LEASE_END_DATE: 'Lease_end_date_updated_to',
  PROGRAM_DISPLAY_NAME: 'programDisplayName',
  SIGN_METHOD: 'signMethod',
};
