/*
 * Copyright (c) 2022 Reva Technology Inc., all rights reserved.
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Licensed under the Elastic License 2.0; you may not use this file except
 * in compliance with the Elastic License 2.0.
 */

import { expect } from 'chai';
import Promise from 'bluebird';
import fs from 'fs';
import path from 'path';
import { buildCorticonScreeningRequest } from '../screening/corticon';

const readFile = Promise.promisify(fs.readFile);

const sampleIndividualScreeningReports = {
  decisionId: '9062c303-c19b-4dbf-9189-d81e5b42e390',
  applicants: [
    {
      memberType: 'resident',
      guarantors: [],
      personId: 'c2897bb4-5d25-43ae-9261-b6a3a69b91a8',
      creditReportStatus: 'completed',
      criminalReportStatus: 'completed',
      hasInternationalAddress: null,
      monthlyIncome: 5000,
      liquidAssets: null,
      creditScore: 738,
      hasTaxLiens: false,
      hasBankruptcy: false,
      hasLegalItems: false,
      hasForeclosure: false,
      hasUtilityDebt: false,
      hasMortgageDebt: false,
      hasSuspiciousSsn: false,
      hasEvictionNotice: false,
      hasLeaseViolation: false,
      hasNsfOrLatePayMax: false,
      hasNsfOrLatePayMin: false,
      hasRentalCollections: false,
      hasPropertyRentalDebt: false,
      hasNoEstablishedCredit: false,
      hasDuiFelony: false,
      hasSexFelony: false,
      hasDrugsFelony: false,
      hasTheftFelony: false,
      hasTrafficFelony: false,
      hasWeaponsFelony: false,
      hasDuiMisdemeanor: false,
      hasPropertyFelony: false,
      hasSexMisdemeanor: false,
      hasGlobalSanctions: false,
      hasDrugsMisdemeanor: false,
      hasTheftMisdemeanor: false,
      hasEvictionFilingsMax: false,
      hasEvictionFilingsMin: false,
      hasEvictionRecordsMax: false,
      hasEvictionRecordsMin: false,
      hasTheftByCheckFelony: false,
      hasTrafficMisdemeanor: false,
      hasUnclassifiedFelony: false,
      hasViolentCrimeFelony: false,
      hasWeaponsMisdemeanor: false,
      hasPropertyMisdemeanor: false,
      hasGlobalSanctionsFuzzy: false,
      hasRegisteredSexOffender: false,
      hasTheftByCheckMisdemeanor: false,
      hasUnclassifiedMisdemeanor: false,
      hasViolentCrimeMisdemeanor: false,
      hasRegisteredSexOffenderDobOnly: false,
    },
    {
      memberType: 'resident',
      guarantors: [],
      personId: '82252d05-56ee-4f56-986e-8feada615146',
      creditReportStatus: 'completed',
      criminalReportStatus: 'completed',
      hasInternationalAddress: null,
      monthlyIncome: 5000,
      liquidAssets: null,
      creditScore: 738,
      hasTaxLiens: false,
      hasBankruptcy: false,
      hasLegalItems: false,
      hasForeclosure: false,
      hasUtilityDebt: false,
      hasMortgageDebt: false,
      hasSuspiciousSsn: false,
      hasEvictionNotice: false,
      hasLeaseViolation: false,
      hasNsfOrLatePayMax: false,
      hasNsfOrLatePayMin: false,
      hasRentalCollections: false,
      hasPropertyRentalDebt: false,
      hasNoEstablishedCredit: false,
      hasDuiFelony: false,
      hasSexFelony: false,
      hasDrugsFelony: false,
      hasTheftFelony: false,
      hasTrafficFelony: false,
      hasWeaponsFelony: false,
      hasDuiMisdemeanor: false,
      hasPropertyFelony: false,
      hasSexMisdemeanor: false,
      hasGlobalSanctions: false,
      hasDrugsMisdemeanor: false,
      hasTheftMisdemeanor: false,
      hasEvictionFilingsMax: false,
      hasEvictionFilingsMin: false,
      hasEvictionRecordsMax: false,
      hasEvictionRecordsMin: false,
      hasTheftByCheckFelony: false,
      hasTrafficMisdemeanor: false,
      hasUnclassifiedFelony: false,
      hasViolentCrimeFelony: false,
      hasWeaponsMisdemeanor: false,
      hasPropertyMisdemeanor: false,
      hasGlobalSanctionsFuzzy: false,
      hasRegisteredSexOffender: false,
      hasTheftByCheckMisdemeanor: false,
      hasUnclassifiedMisdemeanor: false,
      hasViolentCrimeMisdemeanor: false,
      hasRegisteredSexOffenderDobOnly: false,
    },
    {
      memberType: 'occupant',
      guarantors: [],
      personId: 'fe262c9d-1c9b-44c6-81ae-9a64e86547ba',
      creditReportStatus: 'completed',
      criminalReportStatus: 'completed',
      hasInternationalAddress: null,
      monthlyIncome: 5000,
      liquidAssets: null,
      creditScore: 738,
      hasTaxLiens: false,
      hasBankruptcy: false,
      hasLegalItems: false,
      hasForeclosure: false,
      hasUtilityDebt: false,
      hasMortgageDebt: false,
      hasSuspiciousSsn: false,
      hasEvictionNotice: false,
      hasLeaseViolation: false,
      hasNsfOrLatePayMax: false,
      hasNsfOrLatePayMin: false,
      hasRentalCollections: false,
      hasPropertyRentalDebt: false,
      hasNoEstablishedCredit: false,
      hasDuiFelony: false,
      hasSexFelony: false,
      hasDrugsFelony: false,
      hasTheftFelony: false,
      hasTrafficFelony: false,
      hasWeaponsFelony: false,
      hasDuiMisdemeanor: false,
      hasPropertyFelony: false,
      hasSexMisdemeanor: false,
      hasGlobalSanctions: false,
      hasDrugsMisdemeanor: false,
      hasTheftMisdemeanor: false,
      hasEvictionFilingsMax: false,
      hasEvictionFilingsMin: false,
      hasEvictionRecordsMax: false,
      hasEvictionRecordsMin: false,
      hasTheftByCheckFelony: false,
      hasTrafficMisdemeanor: false,
      hasUnclassifiedFelony: false,
      hasViolentCrimeFelony: false,
      hasWeaponsMisdemeanor: false,
      hasPropertyMisdemeanor: false,
      hasGlobalSanctionsFuzzy: false,
      hasRegisteredSexOffender: false,
      hasTheftByCheckMisdemeanor: false,
      hasUnclassifiedMisdemeanor: false,
      hasViolentCrimeMisdemeanor: false,
      hasRegisteredSexOffenderDobOnly: false,
    },
    {
      memberType: 'guarantor',
      guarantors: [],
      personId: '47e19704-6b8c-4df1-ad51-f03fa9ddfca7',
      creditReportStatus: 'completed',
      criminalReportStatus: 'completed',
      hasInternationalAddress: null,
      monthlyIncome: 5000,
      liquidAssets: null,
      creditScore: 738,
      hasTaxLiens: false,
      hasBankruptcy: false,
      hasLegalItems: false,
      hasForeclosure: false,
      hasUtilityDebt: false,
      hasMortgageDebt: false,
      hasSuspiciousSsn: false,
      hasEvictionNotice: false,
      hasLeaseViolation: false,
      hasNsfOrLatePayMax: false,
      hasNsfOrLatePayMin: false,
      hasRentalCollections: false,
      hasPropertyRentalDebt: false,
      hasNoEstablishedCredit: false,
      hasDuiFelony: false,
      hasSexFelony: false,
      hasDrugsFelony: false,
      hasTheftFelony: false,
      hasTrafficFelony: false,
      hasWeaponsFelony: false,
      hasDuiMisdemeanor: false,
      hasPropertyFelony: false,
      hasSexMisdemeanor: false,
      hasGlobalSanctions: false,
      hasDrugsMisdemeanor: false,
      hasTheftMisdemeanor: false,
      hasEvictionFilingsMax: false,
      hasEvictionFilingsMin: false,
      hasEvictionRecordsMax: false,
      hasEvictionRecordsMin: false,
      hasTheftByCheckFelony: false,
      hasTrafficMisdemeanor: false,
      hasUnclassifiedFelony: false,
      hasViolentCrimeFelony: false,
      hasWeaponsMisdemeanor: false,
      hasPropertyMisdemeanor: false,
      hasGlobalSanctionsFuzzy: false,
      hasRegisteredSexOffender: false,
      hasTheftByCheckMisdemeanor: false,
      hasUnclassifiedMisdemeanor: false,
      hasViolentCrimeMisdemeanor: false,
      hasRegisteredSexOffenderDobOnly: false,
    },
  ],
  quotes: [
    {
      quoteId: '6929f465-990e-4a4d-9fd9-3f42271381cb',
      monthlyRent: 2924,
      monthlyTotalRent: 2924,
      termLength: 6,
    },
    {
      quoteId: '6929f465-990e-4a4d-9fd9-3f42271381cb',
      monthlyRent: 2924,
      monthlyTotalRent: 2924,
      termLength: 12,
    },
    {
      quoteId: '147df813-bb3e-423a-a8ba-14083dd4dec1',
      monthlyRent: 2915,
      monthlyTotalRent: 2915,
      termLength: 12,
    },
    {
      quoteId: 'd13ee172-0b61-4b71-9758-9faea12f1919',
      monthlyRent: 2990,
      monthlyTotalRent: 2990,
      termLength: 6,
    },
    {
      quoteId: 'bd421552-db57-447e-9e68-8e0d8fbc5d1f',
      monthlyRent: 2924,
      monthlyTotalRent: 2924,
      termLength: 6,
    },
  ],
  criteria: {},
};

const readScreeningRequest = async filename => {
  const text = await readFile(path.join(__dirname, 'data', 'screening', filename), 'utf8');
  return text;
};

describe('create screeening request', () => {
  let expectedRequest;
  beforeEach(async () => {
    expectedRequest = await readScreeningRequest('expected-request.xml');
  });

  describe('with predefined data', () => {
    it('should return expected request', async () => {
      const party = {};
      const screeningRequest = await buildCorticonScreeningRequest(party, sampleIndividualScreeningReports);
      expect(screeningRequest).to.deep.equal(expectedRequest);
    });
  });
});
