/*
 * Copyright (c) 2022 Reva Technology Inc., all rights reserved.
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Licensed under the Elastic License 2.0; you may not use this file except
 * in compliance with the Elastic License 2.0.
 */

import { toMoment } from '../../../../common/helpers/moment-utils';
import { DATE_US_FORMAT } from '../../../../common/date-constants';

const identity = v => v;
const dateFormatter = (v, opt = {}) => toMoment(v, { timezone: opt.timezone }).format(DATE_US_FORMAT);

/* eslint-disable camelcase */
export const bluemoonFieldMapping = {
  date_of_lease: { mapping: 'LEASECREATEDON', formatter: dateFormatter },
  unit_number: { mapping: 'UNITNAME', formatter: identity },
  address: { mapping: 'UNITADDRESS' },
  resident_1: { mapping: 'LESSEENAME1' },
  resident_2: { mapping: 'LESSEENAME2' },
  resident_3: { mapping: 'LESSEENAME3' },
  resident_4: { mapping: 'LESSEENAME4' },
  resident_5: { mapping: 'LESSEENAME5' },
  resident_6: { mapping: 'LESSEENAME6' },
  occupant_1: { mapping: 'CHILDNAME1' },
  occupant_2: { mapping: 'CHILDNAME2' },
  occupant_3: { mapping: 'CHILDNAME3' },
  occupant_4: { mapping: 'CHILDNAME4' },
  occupant_5: { mapping: 'CHILDNAME5' },
  occupant_6: { mapping: 'CHILDNAME6' },
  lease_begin_date: { mapping: 'LEASEFROM', formatter: dateFormatter },
  lease_end_date: { mapping: 'LEASETO', formatter: dateFormatter },
  rent: { mapping: 'UNITRENT', formatter: identity },
  security_deposit: { mapping: 'UNITDEPOSIT', formatter: identity },
  length_of_lease: { mapping: 'LEASELENGTH' },
  garage_term_start_date: { mapping: 'LEASEFROM', formatter: dateFormatter },
  garage_term_end_date: { mapping: 'LEASETO', formatter: dateFormatter },
  garage_addendum_additional_rent: { mapping: 'TOTALPARKINGRENT', formatter: identity },
  pet_term_start_date: { mapping: 'LEASEFROM', formatter: dateFormatter },
  pet_term_end_date: { mapping: 'LEASETO', formatter: dateFormatter },
  pet_security_deposit: { mapping: 'TOTALPETDEPOSIT', formatter: identity },
  pet_additional_rent: { mapping: 'TOTALPETRENT', formatter: identity },
  pet_one_time_fee: { mapping: 'TOTALPETFEE', formatter: identity },
  pet_name: { mapping: 'PETNAME1' },
  pet_type: { mapping: 'PETTYPE1' },
  pet_breed: { mapping: 'PETBREED1' },
  pet_color: { mapping: 'PETCOLOR1' },
  pet_weight: { mapping: 'PETWEIGHT1' },
  pet_age: { mapping: 'PETAGE1' },
  pet_license_number: { mapping: 'PETLICENSE1' },
  pet_2_name: { mapping: 'PETNAME2' },
  pet_2_type: { mapping: 'PETTYPE2' },
  pet_2_breed: { mapping: 'PETBREED2' },
  pet_2_color: { mapping: 'PETCOLOR2' },
  pet_2_weight: { mapping: 'PETWEIGHT2' },
  pet_2_age: { mapping: 'PETAGE2' },
  pet_2_license_number: { mapping: 'PETLICENSE2' },
  asst_pet_term_start_date: { mapping: 'LEASEFROM', formatter: dateFormatter },
  asst_pet_term_end_date: { mapping: 'LEASETO', formatter: dateFormatter },
  emotional_pet_term_start_date: { mapping: 'LEASEFROM', formatter: dateFormatter },
  emotional_pet_term_end_date: { mapping: 'LEASETO', formatter: dateFormatter },
  parking_begin_date: { mapping: 'LEASEFROM', formatter: dateFormatter },
  parking_end_date: { mapping: 'LEASETO', formatter: dateFormatter },
  parking_monthly_charge: { mapping: 'TOTALPARKINGRENT', formatter: identity },
  vehicle_make_1: { mapping: 'VMAKEMODEL1' },
  vehicle_model_year_1: { mapping: 'VYEAR1' },
  vehicle_state_1: { mapping: 'VSTATE1' },
  vehicle_license_number_1: { mapping: 'VLICPLATE1' },
  parking_space_number_1: { mapping: 'PARKINGSPACE1' },
  vehicle_make_2: { mapping: 'VMAKEMODEL2' },
  vehicle_model_year_2: { mapping: 'VYEAR2' },
  vehicle_state_2: { mapping: 'VSTATE2' },
  vehicle_license_number_2: { mapping: 'VLICPLATE2' },
  parking_space_number_2: { mapping: 'PARKINGSPACE2' },
  vehicle_make_3: { mapping: 'VMAKEMODEL3' },
  vehicle_model_year_3: { mapping: 'VYEAR3' },
  vehicle_state_3: { mapping: 'VSTATE3' },
  vehicle_license_number_3: { mapping: 'VLICPLATE3' },
  parking_space_number_3: { mapping: 'PARKINGSPACE3' },
  addendum_rent_concession_one_time_amount: { mapping: 'TOTALONETIMECONCESSIONAMOUNT', formatter: identity },
  addendum_rent_concession_one_time_months: { mapping: 'ONETIMECONCESSIONAPPLIEDMONTH' },
  addendum_rent_concession_amount: { mapping: 'TOTALRECURRINGCONCESSIONAMOUNT', formatter: identity },
  washer_dryer_rent_begin_date: { mapping: 'LEASEFROM', formatter: dateFormatter },
  washer_dryer_fee: { mapping: 'TOTALAPPLIANCEFEES', formatter: identity },
  resident_1_email: { mapping: 'LESSEEEMAIL1' },
  resident_2_email: { mapping: 'LESSEEEMAIL2' },
  resident_3_email: { mapping: 'LESSEEEMAIL3' },
  resident_4_email: { mapping: 'LESSEEEMAIL4' },
  resident_5_email: { mapping: 'LESSEEEMAIL5' },
  resident_6_email: { mapping: 'LESSEEEMAIL6' },
};
