/*
 * Copyright (c) 2022 Reva Technology Inc., all rights reserved.
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Licensed under the Elastic License 2.0; you may not use this file except
 * in compliance with the Elastic License 2.0.
 */

export const books = [
  {
    title: "Old Man's War",
    author: {
      firstName: 'John',
      lastName: 'Scalzi',
    },
    id: 0,
  },
  {
    title: 'The Lock Artist',
    author: {
      firstName: 'Steve',
      lastName: 'Hamilton',
    },
    id: 1,
  },
  {
    title: 'HTML5',
    author: {
      firstName: 'Remy',
      lastName: 'Sharp',
    },
    id: 2,
  },
  {
    title: 'Right Ho Jeeves',
    author: {
      firstName: 'P.D',
      lastName: 'Woodhouse',
    },
    id: 3,
  },
  {
    title: 'The Code of the Wooster',
    author: {
      firstName: 'P.D',
      lastName: 'Woodhouse',
    },
    id: 4,
  },
  {
    title: 'Thank You Jeeves',
    author: {
      firstName: 'P.D',
      lastName: 'Woodhouse',
    },
    id: 5,
  },
  {
    title: 'The DaVinci Code',
    author: {
      firstName: 'Dan',
      lastName: 'Brown',
    },
    id: 6,
  },
  {
    title: 'Angels & Demons',
    author: {
      firstName: 'Dan',
      lastName: 'Brown',
    },
    id: 7,
  },
  {
    title: 'The Silmarillion',
    author: {
      firstName: 'J.R.R',
      lastName: 'Tolkien',
    },
    id: 8,
  },
  {
    title: 'Syrup',
    author: {
      firstName: 'Max',
      lastName: 'Barry',
    },
    id: 9,
  },
  {
    title: 'The Lost Symbol',
    author: {
      firstName: 'Dan',
      lastName: 'Brown',
    },
    id: 10,
  },
  {
    title: 'The Book of Lies',
    author: {
      firstName: 'Brad',
      lastName: 'Meltzer',
    },
    id: 11,
  },
  {
    title: 'Lamb',
    author: {
      firstName: 'Christopher',
      lastName: 'Moore',
    },
    id: 12,
  },
  {
    title: 'Fool',
    author: {
      firstName: 'Christopher',
      lastName: 'Moore',
    },
    id: 13,
  },
  {
    title: 'Incompetence',
    author: {
      firstName: 'Rob',
      lastName: 'Grant',
    },
    id: 14,
  },
  {
    title: 'Fat',
    author: {
      firstName: 'Rob',
      lastName: 'Grant',
    },
    id: 15,
  },
  {
    title: 'Colony',
    author: {
      firstName: 'Rob',
      lastName: 'Grant',
    },
    id: 16,
  },
  {
    title: 'Backwards, Red Dwarf',
    author: {
      firstName: 'Rob',
      lastName: 'Grant',
    },
    id: 17,
  },
  {
    title: 'The Grand Design',
    author: {
      firstName: 'Stephen',
      lastName: 'Hawking',
    },
    id: 18,
  },
  {
    title: 'The Book of Samson',
    author: {
      firstName: 'David',
      lastName: 'Maine',
    },
    id: 19,
  },
  {
    title: 'The Preservationist',
    author: {
      firstName: 'David',
      lastName: 'Maine',
    },
    id: 20,
  },
  {
    title: 'Fallen',
    author: {
      firstName: 'David',
      lastName: 'Maine',
    },
    id: 21,
  },
  {
    title: 'Monster 1959',
    author: {
      firstName: 'David',
      lastName: 'Maine',
    },
    id: 22,
  },
];

export const users = [
  {
    id: 1,
    first_name: 'Dennis',
    last_name: 'Bowman',
    phone: '33-(613)617-1438',
    email: 'dbowman0@etsy.com',
  },
  {
    id: 2,
    first_name: 'Jean',
    last_name: 'Graham',
    phone: '7-(145)535-4010',
    email: 'jgraham1@soundcloud.com',
  },
  {
    id: 3,
    first_name: 'Todd',
    last_name: 'Boyd',
    phone: '81-(602)843-0722',
    email: 'tboyd2@mapquest.com',
  },
  {
    id: 4,
    first_name: 'Donald',
    last_name: 'Frazier',
    phone: '57-(315)977-9452',
    email: 'dfrazier3@is.gd',
  },
  {
    id: 5,
    first_name: 'Janice',
    last_name: 'Turner',
    phone: '502-(941)714-8211',
    email: 'jturner4@elpais.com',
  },
  {
    id: 6,
    first_name: 'Martin',
    last_name: 'Romero',
    phone: '63-(763)178-7957',
    email: 'mromero5@dagondesign.com',
  },
  {
    id: 7,
    first_name: 'Dennis',
    last_name: 'Pierce',
    phone: '352-(331)144-8253',
    email: 'dpierce6@nature.com',
  },
  {
    id: 8,
    first_name: 'Andrea',
    last_name: 'Watkins',
    phone: '48-(121)225-8027',
    email: 'awatkins7@freewebs.com',
  },
  {
    id: 9,
    first_name: 'Melissa',
    last_name: 'Lewis',
    phone: '81-(776)962-1009',
    email: 'mlewis8@buzzfeed.com',
  },
  {
    id: 10,
    first_name: 'Henry',
    last_name: 'Bryant',
    phone: '591-(694)321-0629',
    email: 'hbryant9@blogtalkradio.com',
  },
  {
    id: 11,
    first_name: 'Heather',
    last_name: 'Walker',
    phone: '62-(249)553-9763',
    email: 'hwalkera@washington.edu',
  },
  {
    id: 12,
    first_name: 'Shawn',
    last_name: 'Reynolds',
    phone: '30-(705)293-6755',
    email: 'sreynoldsb@marriott.com',
  },
  {
    id: 13,
    first_name: 'Lori',
    last_name: 'Carr',
    phone: '387-(881)706-1841',
    email: 'lcarrc@state.gov',
  },
  {
    id: 14,
    first_name: 'Stephanie',
    last_name: 'Hansen',
    phone: '86-(408)394-1897',
    email: 'shansend@blogs.com',
  },
  {
    id: 15,
    first_name: 'Debra',
    last_name: 'Morgan',
    phone: '81-(394)640-8982',
    email: 'dmorgane@biglobe.ne.jp',
  },
  {
    id: 16,
    first_name: 'Betty',
    last_name: 'Romero',
    phone: '36-(702)892-6439',
    email: 'bromerof@wisc.edu',
  },
  {
    id: 17,
    first_name: 'Kimberly',
    last_name: 'Fox',
    phone: '86-(938)225-0748',
    email: 'kfoxg@webeden.co.uk',
  },
  {
    id: 18,
    first_name: 'Phyllis',
    last_name: 'Bowman',
    phone: '351-(523)188-1383',
    email: 'pbowmanh@cmu.edu',
  },
  {
    id: 19,
    first_name: 'Evelyn',
    last_name: 'West',
    phone: '33-(444)942-4188',
    email: 'ewesti@ebay.co.uk',
  },
  {
    id: 20,
    first_name: 'Nancy',
    last_name: 'Mitchell',
    phone: '56-(604)666-3346',
    email: 'nmitchellj@google.ru',
  },
  {
    id: 21,
    first_name: 'Raymond',
    last_name: 'Hansen',
    phone: '86-(984)885-1978',
    email: 'rhansenk@soundcloud.com',
  },
  {
    id: 22,
    first_name: 'Jacqueline',
    last_name: 'Peters',
    phone: '33-(518)640-2163',
    email: 'jpetersl@360.cn',
  },
  {
    id: 23,
    first_name: 'Ruby',
    last_name: 'Richards',
    phone: '86-(481)212-7873',
    email: 'rrichardsm@purevolume.com',
  },
  {
    id: 24,
    first_name: 'George',
    last_name: 'Morris',
    phone: '81-(621)675-6294',
    email: 'gmorrisn@mediafire.com',
  },
  {
    id: 25,
    first_name: 'Carlos',
    last_name: 'Nichols',
    phone: '370-(992)828-4820',
    email: 'cnicholso@forbes.com',
  },
  {
    id: 26,
    first_name: 'Doris',
    last_name: 'Arnold',
    phone: '352-(297)704-0949',
    email: 'darnoldp@is.gd',
  },
  {
    id: 27,
    first_name: 'Paula',
    last_name: 'Ross',
    phone: '86-(900)586-6015',
    email: 'prossq@abc.net.au',
  },
  {
    id: 28,
    first_name: 'Joshua',
    last_name: 'Morris',
    phone: '1-(816)322-6716',
    email: 'jmorrisr@uol.com.br',
  },
  {
    id: 29,
    first_name: 'Brenda',
    last_name: 'Morrison',
    phone: '86-(830)114-8136',
    email: 'bmorrisons@nifty.com',
  },
  {
    id: 30,
    first_name: 'Teresa',
    last_name: 'Diaz',
    phone: '86-(608)508-8064',
    email: 'tdiazt@booking.com',
  },
  {
    id: 31,
    first_name: 'Brandon',
    last_name: 'Fernandez',
    phone: '86-(487)599-1737',
    email: 'bfernandezu@angelfire.com',
  },
  {
    id: 32,
    first_name: 'Steven',
    last_name: 'Kim',
    phone: '380-(230)404-5445',
    email: 'skimv@usnews.com',
  },
  {
    id: 33,
    first_name: 'Sean',
    last_name: 'Lewis',
    phone: '502-(305)863-4198',
    email: 'slewisw@opera.com',
  },
  {
    id: 34,
    first_name: 'Gerald',
    last_name: 'Riley',
    phone: '27-(884)520-4705',
    email: 'grileyx@ning.com',
  },
  {
    id: 35,
    first_name: 'Susan',
    last_name: 'Franklin',
    phone: '62-(369)724-4229',
    email: 'sfrankliny@omniture.com',
  },
  {
    id: 36,
    first_name: 'Jerry',
    last_name: 'Williams',
    phone: '63-(449)526-8591',
    email: 'jwilliamsz@lycos.com',
  },
  {
    id: 37,
    first_name: 'Joyce',
    last_name: 'Martin',
    phone: '63-(722)583-2757',
    email: 'jmartin10@dailymotion.com',
  },
  {
    id: 38,
    first_name: 'Earl',
    last_name: 'Reid',
    phone: '56-(984)991-9055',
    email: 'ereid11@gravatar.com',
  },
  {
    id: 39,
    first_name: 'Tina',
    last_name: 'Jackson',
    phone: '82-(694)586-6398',
    email: 'tjackson12@psu.edu',
  },
  {
    id: 40,
    first_name: 'Raymond',
    last_name: 'Adams',
    phone: '7-(858)821-4291',
    email: 'radams13@blogger.com',
  },
  {
    id: 41,
    first_name: 'Sara',
    last_name: 'Jenkins',
    phone: '351-(190)626-0457',
    email: 'sjenkins14@theguardian.com',
  },
  {
    id: 42,
    first_name: 'Alice',
    last_name: 'Sims',
    phone: '63-(481)499-3471',
    email: 'asims15@123-reg.co.uk',
  },
  {
    id: 43,
    first_name: 'Albert',
    last_name: 'Howell',
    phone: '33-(365)528-4913',
    email: 'ahowell16@google.de',
  },
  {
    id: 44,
    first_name: 'Wayne',
    last_name: 'Murphy',
    phone: '93-(951)184-3915',
    email: 'wmurphy17@mtv.com',
  },
  {
    id: 45,
    first_name: 'Frank',
    last_name: 'Willis',
    phone: '1-(949)286-5504',
    email: 'fwillis18@spotify.com',
  },
  {
    id: 46,
    first_name: 'Teresa',
    last_name: 'Ramirez',
    phone: '86-(956)162-1143',
    email: 'tramirez19@sogou.com',
  },
  {
    id: 47,
    first_name: 'Annie',
    last_name: 'Moore',
    phone: '267-(434)780-9024',
    email: 'amoore1a@indiatimes.com',
  },
  {
    id: 48,
    first_name: 'Rebecca',
    last_name: 'Webb',
    phone: '970-(930)493-0757',
    email: 'rwebb1b@ftc.gov',
  },
  {
    id: 49,
    first_name: 'Cheryl',
    last_name: 'Barnes',
    phone: '46-(709)377-9751',
    email: 'cbarnes1c@alexa.com',
  },
  {
    id: 50,
    first_name: 'Shirley',
    last_name: 'Butler',
    phone: '353-(194)956-4182',
    email: 'sbutler1d@yale.edu',
  },
  {
    id: 51,
    first_name: 'Anthony',
    last_name: 'Johnston',
    phone: '976-(477)870-3005',
    email: 'ajohnston1e@cargocollective.com',
  },
  {
    id: 52,
    first_name: 'Stephanie',
    last_name: 'Hall',
    phone: '62-(632)282-0051',
    email: 'shall1f@live.com',
  },
  {
    id: 53,
    first_name: 'Margaret',
    last_name: 'Kelley',
    phone: '45-(844)721-7249',
    email: 'mkelley1g@elegantthemes.com',
  },
  {
    id: 54,
    first_name: 'Gary',
    last_name: 'Price',
    phone: '7-(552)420-2341',
    email: 'gprice1h@cbslocal.com',
  },
  {
    id: 55,
    first_name: 'Rebecca',
    last_name: 'Foster',
    phone: '62-(780)494-3883',
    email: 'rfoster1i@hp.com',
  },
  {
    id: 56,
    first_name: 'Martha',
    last_name: 'Watson',
    phone: '55-(845)330-3517',
    email: 'mwatson1j@webeden.co.uk',
  },
  {
    id: 57,
    first_name: 'Larry',
    last_name: 'Rodriguez',
    phone: '1-(939)887-0364',
    email: 'lrodriguez1k@wired.com',
  },
  {
    id: 58,
    first_name: 'Bruce',
    last_name: 'Carr',
    phone: '385-(711)441-5168',
    email: 'bcarr1l@google.de',
  },
  {
    id: 59,
    first_name: 'Michelle',
    last_name: 'Morales',
    phone: '48-(523)279-1514',
    email: 'mmorales1m@ovh.net',
  },
  {
    id: 60,
    first_name: 'Juan',
    last_name: 'Rogers',
    phone: '1-(719)909-0397',
    email: 'jrogers1n@cdc.gov',
  },
  {
    id: 61,
    first_name: 'Jessica',
    last_name: 'Schmidt',
    phone: '52-(402)405-6276',
    email: 'jschmidt1o@answers.com',
  },
  {
    id: 62,
    first_name: 'Justin',
    last_name: 'Ortiz',
    phone: '380-(674)145-3059',
    email: 'jortiz1p@merriam-webster.com',
  },
  {
    id: 63,
    first_name: 'Jacqueline',
    last_name: 'Flores',
    phone: '81-(665)780-3712',
    email: 'jflores1q@symantec.com',
  },
  {
    id: 64,
    first_name: 'Ronald',
    last_name: 'Mcdonald',
    phone: '353-(974)540-7052',
    email: 'rmcdonald1r@de.vu',
  },
  {
    id: 65,
    first_name: 'Angela',
    last_name: 'King',
    phone: '53-(853)125-2902',
    email: 'aking1s@hexun.com',
  },
  {
    id: 66,
    first_name: 'Kathryn',
    last_name: 'Wilson',
    phone: '86-(370)200-3414',
    email: 'kwilson1t@yelp.com',
  },
  {
    id: 67,
    first_name: 'Harry',
    last_name: 'Reyes',
    phone: '7-(764)635-8817',
    email: 'hreyes1u@cdbaby.com',
  },
  {
    id: 68,
    first_name: 'George',
    last_name: 'Roberts',
    phone: '86-(147)929-5889',
    email: 'groberts1v@google.pl',
  },
  {
    id: 69,
    first_name: 'Jacqueline',
    last_name: 'Ferguson',
    phone: '351-(791)155-3413',
    email: 'jferguson1w@army.mil',
  },
  {
    id: 70,
    first_name: 'Kimberly',
    last_name: 'Shaw',
    phone: '36-(648)884-2999',
    email: 'kshaw1x@redcross.org',
  },
  {
    id: 71,
    first_name: 'Kelly',
    last_name: 'Ramos',
    phone: '82-(910)168-0335',
    email: 'kramos1y@indiatimes.com',
  },
  {
    id: 72,
    first_name: 'Sean',
    last_name: 'Castillo',
    phone: '86-(891)177-3377',
    email: 'scastillo1z@wordpress.com',
  },
  {
    id: 73,
    first_name: 'Roger',
    last_name: 'Lawson',
    phone: '92-(695)116-2997',
    email: 'rlawson20@tripadvisor.com',
  },
  {
    id: 74,
    first_name: 'Norma',
    last_name: 'Dixon',
    phone: '86-(985)330-0710',
    email: 'ndixon21@craigslist.org',
  },
  {
    id: 75,
    first_name: 'Bonnie',
    last_name: 'Payne',
    phone: '48-(977)636-4935',
    email: 'bpayne22@mlb.com',
  },
  {
    id: 76,
    first_name: 'William',
    last_name: 'Willis',
    phone: '595-(273)131-8369',
    email: 'wwillis23@paypal.com',
  },
  {
    id: 77,
    first_name: 'Jonathan',
    last_name: 'Harvey',
    phone: '84-(356)932-1048',
    email: 'jharvey24@hugedomains.com',
  },
  {
    id: 78,
    first_name: 'Donald',
    last_name: 'Castillo',
    phone: '62-(238)911-2370',
    email: 'dcastillo25@a8.net',
  },
  {
    id: 79,
    first_name: 'Anna',
    last_name: 'Edwards',
    phone: '234-(837)696-9736',
    email: 'aedwards26@admin.ch',
  },
  {
    id: 80,
    first_name: 'Billy',
    last_name: 'Sanchez',
    phone: '62-(284)623-5595',
    email: 'bsanchez27@netvibes.com',
  },
  {
    id: 81,
    first_name: 'Teresa',
    last_name: 'Gutierrez',
    phone: '998-(917)421-4804',
    email: 'tgutierrez28@desdev.cn',
  },
  {
    id: 82,
    first_name: 'Susan',
    last_name: 'Williamson',
    phone: '502-(764)727-4824',
    email: 'swilliamson29@eepurl.com',
  },
  {
    id: 83,
    first_name: 'Donna',
    last_name: 'Greene',
    phone: '86-(347)761-4938',
    email: 'dgreene2a@ftc.gov',
  },
  {
    id: 84,
    first_name: 'Andrea',
    last_name: 'Larson',
    phone: '86-(198)662-5772',
    email: 'alarson2b@cargocollective.com',
  },
  {
    id: 85,
    first_name: 'Earl',
    last_name: 'Owens',
    phone: '84-(620)562-3624',
    email: 'eowens2c@flavors.me',
  },
  {
    id: 86,
    first_name: 'Jane',
    last_name: 'Marshall',
    phone: '86-(426)116-8609',
    email: 'jmarshall2d@woothemes.com',
  },
  {
    id: 87,
    first_name: 'Paul',
    last_name: 'West',
    phone: '595-(961)867-5703',
    email: 'pwest2e@sciencedirect.com',
  },
  {
    id: 88,
    first_name: 'Diana',
    last_name: 'Cruz',
    phone: '81-(898)378-8698',
    email: 'dcruz2f@home.pl',
  },
  {
    id: 89,
    first_name: 'Sarah',
    last_name: 'Moreno',
    phone: '51-(787)515-4767',
    email: 'smoreno2g@cocolog-nifty.com',
  },
  {
    id: 90,
    first_name: 'Emily',
    last_name: 'Ellis',
    phone: '57-(718)376-3430',
    email: 'eellis2h@archive.org',
  },
  {
    id: 91,
    first_name: 'Timothy',
    last_name: 'Moreno',
    phone: '1-(916)751-3564',
    email: 'tmoreno2i@fc2.com',
  },
  {
    id: 92,
    first_name: 'Thomas',
    last_name: 'Gibson',
    phone: '218-(209)255-8434',
    email: 'tgibson2j@oaic.gov.au',
  },
  {
    id: 93,
    first_name: 'Dorothy',
    last_name: 'Coleman',
    phone: '86-(319)357-9898',
    email: 'dcoleman2k@jugem.jp',
  },
  {
    id: 94,
    first_name: 'Carolyn',
    last_name: 'Fox',
    phone: '62-(825)926-8352',
    email: 'cfox2l@ca.gov',
  },
  {
    id: 95,
    first_name: 'James',
    last_name: 'Allen',
    phone: '86-(258)373-0487',
    email: 'jallen2m@squidoo.com',
  },
  {
    id: 96,
    first_name: 'Patricia-Andrea',
    last_name: "O'reilly",
    phone: '46-(448)968-6355',
    email: 'privera2n@usatoday.com',
  },
  {
    id: 97,
    first_name: 'Douglas',
    last_name: 'Anderson',
    phone: '255-(351)200-6996',
    email: 'danderson2o@latimes.com',
  },
  {
    id: 98,
    first_name: 'Gary',
    last_name: 'Tucker',
    phone: '46-(666)858-9701',
    email: 'gtucker2p@simplemachines.org',
  },
  {
    id: 99,
    first_name: 'Judith',
    last_name: 'Campbell',
    phone: '380-(394)678-4691',
    email: 'jcampbell2q@msn.com',
  },
  {
    id: 100,
    first_name: 'Lawrence',
    last_name: 'Hughes',
    phone: '63-(290)909-8495',
    email: 'lhughes2r@mac.com',
  },
];
